### ISSUE TITLE
minetype?

### ISSUE THREAD

**Issue by sloria** [webpack-contrib/url-loader#10]
Just curious: why handle "minetype" here: https://github.com/webpack/url-loader/blob/master/index.js#L14 ? It seems unnecessary and may encourage bad spelling.

**Comment by sokra** [comment]
For backward compatibility. It was initially spelled wrong. You can to a PR which throws an error when minetype is used.

**Comment by michael-ciniawsky** [comment]
😆 Will be fixed by #70 (I removed it ignorantly) and it will be semver major release anyways

**Comment by robwierzbowski** [comment]
I was wondering the same thing 😄
