### ISSUE TITLE
url-loader not working when having an unclosed quote inside multiple-lines' comment

### ISSUE THREAD

**Issue by amitayr** [webpack-contrib/url-loader#100]
i was having a strange problem - some of the images included in my application's scss files, weren't handled by the url loader.

my current configuration of url-loader is this:
```
{
    test: /\.(jpg|png|gif|ttf|txt|svg)/,
    loader: "url-loader",
    query: "limit=10&name=images/[name][md5:hash:hex:3].[ext]&publicPath=./",
},
```
so all css rules with "background-image" of images large enough should be collected into my "dist/images" folder and their url should be replaced with their url inside "dist/images".
however, although some of the images were indeed collected into "dist/images", some didn't, and stayed with their original url.

after some exhausting checks, i found out that it happans to all the url's after one comment in my scss file:
```
/**
 * Fix the cursor style for Chrome's increment/decrement buttons. For certain (etc.)
 */
```
apparently, when i have an single or double quote inside a multiple lines' comment, something is messed up, and all the url afterwards are not handled by the url-loader.
**important:** if i close the quote (e.g. " Fix the cursor style for 'Chrome'") this bug does not reproduce.
(of cource, removing the quote solve it as well, this is what i did...)

this bug does not reproduce when i run a production build, i.e. run webpack with "-p" flag.

i am using webpack version 2.2.1, with url-loader version 0.5.7

**Comment by evilebottnawi** [comment]
@amitayr can you provide minimum reproducible test repo?

**Comment by michael-ciniawsky** [comment]
Feel free to reopen when a reproduction repo is provided
