### ISSUE TITLE
Http links?

### ISSUE THREAD

**Issue by geoshar** [webpack-contrib/url-loader#103]
Is there a way to do the same thing with HTTP links?
for example:
`https://fonts.gstatic.com/s/roboto/v18/ek4gzZ-GeXAPcSbHtCeQI_esZW2xOQ-xsNqO47m55DA.woff2`

**Comment by michael-ciniawsky** [comment]
Nope, `webpack` relies on the file system, you can only fetch additional data within a loader, but a source file (even if empty) must exist when using a loader to my knowledge

**Comment by geoshar** [comment]
Ok, thank you.
