### ISSUE TITLE
Unable to load iconic fonts

### ISSUE THREAD

**Issue by jeusdi** [webpack-contrib/url-loader#107]
I've installed font-awesome:

    npm install font-awesome

I've added these rules on webconfig:

    { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
    { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }

Into my `main.scss` I've added this import:

    @import "font-awesome/scss/font-awesome.scss";

`font-awesome` css rules are loaded but, fonts are not loaded.

It seems fonts are requested by browser:

[![enter image description here][1]][1]

However, the response is the main html page:

[![enter image description here][2]][2]

Any ideas?

  [1]: https://i.stack.imgur.com/cbJdR.png
  [2]: https://i.stack.imgur.com/LCUgy.png

**Comment by evilebottnawi** [comment]
@jeusdi seems something wrong in version or configuration. Can you create minimum reproducible test repo?

**Comment by jeusdi** [comment]
Here you can pull my current code: [repository link](https://github.com/jeusdi/fontawesome).

In order to reproduce it:

    yarn start
    go to localhost:3000

Then, you are going to see above image

**Comment by michael-ciniawsky** [comment]
Did your resolve this ? What's the status here ? :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky resolve this in near future :+1:
