### ISSUE TITLE
Pass options through to fallback

### ISSUE THREAD

**Issue by djbingham** [webpack-contrib/url-loader#108]
Hello! Thanks for the great plugin.

When setting a file size limit for url-loader, I'd like to also set my own file naming pattern for files exceeding the limit. The default fallback (file-loader) has a `name` option which I've used in the past but, looking at line 44 of `index.js`, it seems that there's no attempt to pass any options through to the fallback loader.

Is this something that could easily be added?

**Comment by evilebottnawi** [comment]
@djbingham can you describe use case?

**Comment by djbingham** [comment]
Basically, I wanted to add a hash into the file name for cache-busting, like this:

```
{
    loader: 'file-loader',
    options: {
        name: '[path][name].[hash].[ext]'
    }
}
```

However, I've since realised that invalidates all of the caching within the build process, which is absolutely not what I want, so that seems like a bad idea. I'll have to rethink my cache-busting strategy.

**Comment by milushov** [comment]
@evilebottnawi  @michael-ciniawsky 
Hey, guys, I have the same problem

Is it possible to pass `options` to the `fallback` loader? For example to the `file-loader` in case if I want to set `name` option. 

This code not working:

```coffee
_fileLoaderName =
  name: (
    if forProduction
      '[name].[ext]?[hash]'
    else
      '[name].[ext]'
  )

urlLoader =
  test: /\.(jpe?g|png|gif|ico)$/
  use: [
    loader: 'url-loader'
    options: {
      limit: 8192 # 8 Kb
      fallback: "file-loader?#{JSON.stringify(_fileLoaderName)}"
    }
  ]
```
I've seen code [here](https://github.com/webpack-contrib/url-loader/blob/08135bcee2b187124016f9edbbe6f0f35ce2cb54/src/index.js#L42), should we update logic of the `url-uploader` to support this feature or how can we achieve same result?

To support something like this:

```coffee
_fileLoader =
  loader: 'file-loader'
  options: {
    name: (
      if forProduction
        '[name].[ext]?[hash]'
      else
        '[name].[ext]'
    )

urlLoader =
  test: /\.(jpe?g|png|gif|ico)$/
  use: [
    loader: 'url-loader'
    options: {
      limit: 8192 # 8 Kb
      fallback: _fileLoader
    }
  ]
```

**Comment by vipcxj** [comment]
Is this issue solved? Why did it be closed?

**Comment by milushov** [comment]
¯\_(ツ)_/¯
