### ISSUE TITLE
Different paths per loader

### ISSUE THREAD

**Issue by faustbrian** [webpack-contrib/url-loader#109]
I have a `base` html tag in my document and reference files via `src="assets/bla.css"` instead of `src="/assets/bla.css"` **(note the leading /)**.

The issue that causes is that the url-loader references fonts via `assets/fonts/bla.otf` instead of `/assets/fonts/bla.otf` inside a CSS file which then causes the browser to try to load the font from `/assets/css/assets/fonts/bla.otf`.

Is there some way to tell the url loader how to reference the file inside the CSS file so that it would use a leading **/**?

```js
output: {
  publicPath: ''
},

{
  test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
  loader: 'url-loader',
  options: {
    limit: 10000,
    name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
  }
}
```

**Comment by michael-ciniawsky** [comment]
In case the `asset` exceeds the limit the `file-loader` is used which provides options for this (see the `file-loader` README). `publicPath` should default to `'/'`, since the `file-loader` will generate a URL looking like this

```js
module.exports = __webpack_public_path__ + url
```

**Comment by michael-ciniawsky** [comment]
You can pass all  `file-loader` options to `url-loader` like you already did with `name`

**Comment by faustbrian** [comment]
The issue is that the paths inside the CSS are relative to the CSS file itself so unless I manually go into the CSS file and prefix the font paths with a `/` it will try to load them from a wrong path.

That is why I am asking if there is a way to specify 1 path that is used for output and 1 format that is used inside the CSS. I basically want to tell Webpack to prefix all font paths inside a CSS file `/`.

**Comment by michael-ciniawsky** [comment]
Thats what the `file-loader` && `css-loader` should do already. `webpack` picks up the relative path and replaces it with the `output` path of the asset in the CSS

**Comment by faustbrian** [comment]
Solved it by setting the domain as `publicPath`.
