### ISSUE TITLE
Webpack 4: incorrect peer dependency

### ISSUE THREAD

**Issue by gustavovnicius** [webpack-contrib/url-loader#122]
When using `url-loader` with webpack 4 it gives this warning:

`warning "url-loader > schema-utils@0.4.3" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".`

It's similar to this one: https://github.com/webpack-contrib/style-loader/issues/307

**Comment by evilebottnawi** [comment]
@gustavovnicius `npm/yarn cache clear && npm install`, also check you lock files.

**Comment by asfernandes** [comment]
url-loader 1.0.1 is using schema-utils 0.4.3 which has the dependency "webpack@^2.0.0 || ^3.0.0". Even cleaning the cache the problem is happening.

Shouldn't you update to schema-utils 0.4.5?

**Comment by nypinstripes** [comment]
@gustavovnicius please update schema-utils dep to 0.4.5 which has the webpack 4 dependency fix for:

```warning "url-loader > schema-utils@0.4.3" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".```

```
"peerDependencies": {
     "webpack": "^2.0.0 || ^3.0.0 || ^4.0.0"	     "webpack": "^2.0.0 || ^3.0.0 || ^4.0.0"
 }
```

![screen shot 2018-05-26 at 12 41 58 am](https://user-images.githubusercontent.com/1851296/40572594-142aa2ec-607e-11e8-9fff-9552c638618f.png)

https://yarnpkg.com/en/package/schema-utils

**Comment by nypinstripes** [comment]
@evilebottnawi @michael-ciniawsky maybe this could be re-opened. thanks.

**Comment by evilebottnawi** [comment]
@nypinstripes all already updates, just update you deps and lock file
