### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by hipstermojo** [webpack-contrib/url-loader#127]
The mime dependency has a RegEx Denial of Service vulnerability when I run `npm audit` and I was wondering if you guys had any plans of changing this.

**Comment by Pimm** [comment]
`url-loader` 1.0.1 depends on `mime` ^2.0.3, which shouldn't be vulnerable according to broofa/node-mime#167. Are you on 1.0.1?

**Comment by evilebottnawi** [comment]
@hipstermojo please update you `url-loader` to latest versin
