### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by gustavovnicius** [webpack-contrib/url-loader#132]
It seems to me that `schema-utils` dep was updated a little while ago, although it wasn't published on npm. I'm getting some annoying warnings after upgrading to webpack 4. What's the plan? Can't a new version be published after #129?

**Comment by evilebottnawi** [comment]
@gustavovnicius what warnings you got?

**Comment by PallasKatze** [comment]
Same here:
> warning "url-loader > schema-utils@0.4.3" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0"

**Comment by gustavovnicius** [comment]
BTW @evilebottnawi it's still not published on `npm` (it is the original issue).
<img width="483" alt="screen shot 2018-08-14 at 15 53 39" src="https://user-images.githubusercontent.com/2379486/44095927-48a01dc2-9fda-11e8-8b79-3d98498b26dd.png">

The `schema-utils` dep was updated before, the `package.json` version upped, but no publishing.

**Comment by evilebottnawi** [comment]
@gustavovnicius problem with npm/network, i will try again in near time
