### ISSUE TITLE
Need for `utils/normalizeFallback`

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/url-loader#144]
I think `utils/normalizeFallback` is not needed and we should revert the logic in `src/index.js` back to just `fallback.call(this, src)` since we need to pass all options anyways as it seems e.g

**`webpack.config.js`**
```js
{
  loader; 'url-loader',
  options: {
      limit: 1,
      name: '',
      fallback: 'x-loader',
      any: '',
      option: '',
      you: '',
      want: '',
  }
}
```

should be sufficient

Since https://github.com/webpack-contrib/url-loader/pull/139 all options are again passed to the fallback loader (default && custom), so in case I don't misunderstand the logic in `utils/normalizeFallback` this change basically neglects all extra 'work' we are currently doing there. 

Someone please correct me if I'm wrong 😛

**Comment by evilebottnawi** [comment]
WIP on this

**Comment by Pimm** [comment]
It supports the behaviour proposed/requested in #108 #118.

Essentially, it allows your example to be written in a way which feels more consistent and hygienic to me:
```
{
  loader: 'url-loader',
  options: {
    limit: 1,
    fallback: {
      loader: 'x-loader',
      options: {
        name: '',
        any: '',
        option: '',
        you: '',
        want: '',
      }
    }
  }
}
```

As a bonus, it supports the unlikely edge case in which option names would otherwise collide:
```
{
  loader: 'url-loader',
  options: {
    limit: 1,
    fallback: {
      loader: 'x-loader',
      options: {
        limit: 5
      }
    }
  }
}
```

**Comment by michael-ciniawsky** [comment]
I see, but then we need to remove the default fallback handling from it and apply it only for a custom fallback since this causes issue with current workflows in conjunction with the `file-loader`. #139 ould need to be 'reverted' asell then sinc passing all options is not the goal of `utils/normalizeFallback` ?

**Comment by Pimm** [comment]
Do you have an example of an issue which is still reproducible after #139?

**Comment by evilebottnawi** [comment]
Please wait i will send PR in near time

**Comment by michael-ciniawsky** [comment]
? :) Nope it fixed the current issues, but I as under the impression that passing **all** options was not the original intend here (only pass `options.fallback.options`) ? Or is it mainly about being able to pass an `{Object}` to `options.fallback` `fallback: { loader: 'x-loader', options: {} }`. In this case  #139 should be sufficient and it's resolved already (pending release) ? 

But let's wait for the PR and continue discussion there then please :)
