### ISSUE TITLE
Issue with default fallback options

### ISSUE THREAD

**Issue by JoseGoncalves** [webpack-contrib/url-loader#146]
The following working config in 1.0.1:
```
{
	test: /\.(png|jpg|gif|svg)$/,
	loader: 'url-loader',
	options: {
		limit: 2048,
		name: 'img/[name].[hash:8].[ext]'
	}
}
```
does not work with version 1.1.0, i.e., the 'name' option is not passed to the default fallback 'file-loader'.
Is this on purpose or is it a bug?

**Comment by michael-ciniawsky** [comment]
It is a known bug please pin your version to `< v1.1.0` for now :). It's already fixed on `master` but pending a release
