### ISSUE TITLE
webpack 3 compatibility

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack-contrib/url-loader#147]
Is url-loader@1.1.1 really not compatible any more with webpack 3 ? (like suggested in the package file 
https://github.com/webpack-contrib/url-loader/blob/v1.1.1/package.json#L42) ?

**Comment by michael-ciniawsky** [comment]
It is compatible, the `peerDependency` is just wrong/unneeded. In my opinion it should simply be relaxed, but there doesn't seem to be consensus to make this change (see https://github.com/webpack-contrib/url-loader/issues/142)

**Comment by michael-ciniawsky** [comment]
Just ignore the warning

**Comment by FranckFreiburger** [comment]
ok thanks !

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we close issue?
