### ISSUE TITLE
Specifying `engines` in package.json should be a major update

### ISSUE THREAD

**Issue by kyleoliveiro** [webpack-contrib/url-loader#149]
In `v1.1.0`, `engines` was added to package.json, while it was absent in prior versions.

I'm running Node version `v8.5.0` on my CI server, and my pipeline is breaking now because of this change. Unfortunately I can't simply lock the version `url-loader@1.0.1` in my package.json, as multiple important packages I'm using have `url-loader@^1.0.1` as a dependency.

**Comment by evilebottnawi** [comment]
@michael-ciniawsky what the hell you doing?

**Comment by kyleoliveiro** [comment]
Thanks for the advice. I'm working with the maintainer of the Docker image I'm using in my CI pipeline to bump the Node version to latest LTS.
