### ISSUE TITLE
Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by JGProg** [webpack-contrib/url-loader#158]
Hi everyone !

I have a problem when I would like to export with Webpack !
I have a multiple error :/ 

```
ERROR in ./node_modules/mdbreact/dist/font/roboto/Roboto-Bold.woff2
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
TypeError: Cannot read property 'context' of undefined
```
 
I don't understand why...
See my package.json I try to add option but no change..

var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

module.exports = {
    entry: './src/index.jsx',
    output: {
        path: path.resolve('dist'),
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['.js', '.jsx']
    },
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015', 'stage-3']
                }
            },
			{ test: /\.css$/, loader: "style-loader!css-loader" },
			{
        test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'file-loader',
		  options: {
			context: process.cwd()
		  }
      },
      {
        test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          mimetype: 'application/font-woff'
        }
      },
      {
        test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url-loader',
        query: {
          limit: '10000',
          mimetype: 'application/octet-stream'
        }
      },
      
      {
        test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'svg-url-loader?limit=10000',
        query: {
          limit: '10000',
          mimetype: 'application/svg+xml'
        }
      },
      {
        test: /\.(png|jpg|gif)$/,
        loader: 'url-loader?limit=10000',
        query: {
          limit: 8192
        }
      },
      {
        test: /\.ico(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url-loader?limit=10000'
      }
        ]
    },
    plugins: [new HtmlWebpackPlugin({
        template: './src/index.html',
        filename: 'index.html',
        inject: 'body'
    })],
    devServer: {
        historyApiFallback: true
    },
    externals: {
        // global app config object
        config: JSON.stringify({
            apiUrl: 'http://localhost:4000'
        })
    }
}

My versions :
webpack -v
4.20.2
node -v
v10.11.0
npm -v
6.4.1

Thank you for your help !

**Comment by JGProg** [comment]
Ok sorry ! 

Explain my issue so !
When I run this command : 
`webpack --progress --config webpack.config.js --display-error-details`

I have multiple issue due to 
`RROR in ./node_modules/mdbreact/dist/font/roboto/Roboto-Medium.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)`

I change my configuration on package json (see on another website...) :
`{
      test: /\.(ttf|woff|eot|svg|png|woff2|gif|jpg)(\?[\s\S]+)?$/,
      loader: 'url-loader'
    }`

So it's ok... I have now this error :

ERROR in   TypeError: compilation.templatesPlugin is not a function
- SetVarMainTemplatePlugin.js:17 SetVarMainTemplatePlugin.apply

I don't understand..

**Comment by evilebottnawi** [comment]
@JGProg looks you have invalid configuration
> You may need an appropriate loader to handle this file type.

No loader for `woff2`

**Comment by JGProg** [comment]
How to load this ?

**Comment by evilebottnawi** [comment]
@JGProg add loader for `woff2`, **please** create minimum reproducible test repo on github, i can't help you using config from `issue` - it is **hard** to read and analyze what is wrong

**Comment by JGProg** [comment]
Do you have a bitbucket cloud account ? 

My repo it's on this website.

**Comment by evilebottnawi** [comment]
@JGProg no, i don't have `bitbucket` account

**Comment by JGProg** [comment]
Ok I transfert my depot on Github. Just a moment please, sorry..

Anyway, thank you.

Transfert ok ! My depot it's here : https://github.com/JGProg/testP

**Comment by evilebottnawi** [comment]
@JGProg you repo doesn't work, also please create **minimum** repo, no need copy/paste `CRA`, also you should include `file-loader/url-loader` in your `package.json`

**Comment by JGProg** [comment]
Sorry I'm not yet very comfortable with webpack..

I try it to reduce my project..

**Comment by evilebottnawi** [comment]
@JGProg friendly ping

**Comment by decadef20** [comment]
Same error here. I fixed it by upgrading file-loader

**Comment by conradoramalho** [comment]
Same error here. Any solution?

**Comment by evilebottnawi** [comment]
@conradoramalho Please create minimum reproducible test repo

**Comment by conradoramalho** [comment]
I added file-loader and this solved my problem.

**Comment by evilebottnawi** [comment]
As i said above loader not found for `woff2`
