### ISSUE TITLE
The dataURL of encoded image cant be resolved (decoded) by base64 decoder

### ISSUE THREAD

**Issue by flopsySong** [webpack-contrib/url-loader#159]
version 1.1.2
![image](https://user-images.githubusercontent.com/12528156/47214491-ac2ba580-d3d0-11e8-9131-02da159960aa.png)

**Comment by evilebottnawi** [comment]
@flopsySong please describe your problem (error output, full config, minimum reproducible test repo)

**Comment by flopsySong** [comment]
> @flopsySong please describe your problem (error output, full config, minimum reproducible test repo)

`const merge = require('webpack-merge')
const webpack = require('webpack')
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CleanWebpackPlugin = require('clean-webpack-plugin')

module.exports = merge(
  {},
  {
    mode: 'development',
    entry: {
      main: './src/app.js'
    },
    output: {
      path: path.resolve(__dirname, '../dist'),
      publicPath: '/',
      filename: '[name].js'
      // chunkFilename: '[name].[chunkhash].js'
    },
    module: {
      rules: [
        {
          test: /\.jsx$/,
          loader: 'babel-loader',
          exclude: /node_modules/
        },
        {
          test: /\.js$/,
          loader: 'babel-loader',
          exclude: [path.join(__dirname, '../node_modules')]
        },
        {
          test: /\.(png|jpg|gif|jpeg)$/i,
          use: [
            {
              loader: 'url-loader',
              options: {
                limit: 81920
              }
            }
          ]
        },
        {
          test: /\.scss$/,
          use: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader']
        }
      ]
    },
    // devtool: 'inline-source-map',
    devServer: {
      contentBase: path.join(__dirname, '../dist'),
      host: 'localhost',
      port: 9001,
      hot: true,
      disableHostCheck: true
      // https: true
    },
    plugins: [
      new CleanWebpackPlugin(['dist'], { root: process.cwd() }),
      new HtmlWebpackPlugin({
        title: 'JCloud BI',
        inject: 'body', // inject into bottom of the body
        template: path.join(__dirname, '../src/template.html'),
        favicon: path.join(__dirname, '../favicon.ico')
      }),
      new webpack.HotModuleReplacementPlugin() // for dev mode
    ]
  }
)
`


here is the webpack4 configuration (dev mode), I didnt get any error message, but the image cannot be loaded. 
So I try to get the generated dataURL in web browser, I found that the dataURL cant be decoded by base64

**Comment by evilebottnawi** [comment]
@flopsySong there are a lot of problems why image doesn't show, you need provide more information
