### ISSUE TITLE
missing images when updating the size limmit

### ISSUE THREAD

**Issue by ivoTsolov** [webpack-contrib/url-loader#160]
when i run my project with some options { limit : 2000 }  for example  and i later change the file limits on 4000 for example and then  build and start my app seems like i am missing pictures, also my manifest file is smaller  anyone has similar experience like mine ? and  if so how do i prevent that from happening, my col

**Comment by evilebottnawi** [comment]
@ivoTsolov I can't understand you

**Comment by trusktr** [comment]
Me too. I set `limit: Number.MAX_VALUE`, and when I import images, the import is always `undefined`.

Any ideas why the import is undefined?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/url-loader/issues/161 due issue have example and good describe.
