### ISSUE TITLE
Importing an image is `undefined`

### ISSUE THREAD

**Issue by trusktr** [webpack-contrib/url-loader#161]
When I import an image, the import value is `undefined`. This is my config:

```js
			{
				test: /\.(png|jpg)$/,
				use: [
					{
						loader: 'url-loader',
						options: {
							limit: Number.MAX_VALUE
						},
					},
				],	
			}
```

I'm importing like this:

```js
import logo from '../path/to/foo.png'
```

Any idea why when I import a png file, the import value is `undefined`?

The path is correct. If I change to `file-loader`, then I get a hash like `asdfkhaoienufa984fh9wevnq2of.png` as the import value.

**Comment by evilebottnawi** [comment]
@trusktr can't reproduce please create minimum reproducible test repo, thanks!

**Comment by trusktr** [comment]
Will reproduce when I run into it again.

**Comment by evilebottnawi** [comment]
@trusktr please create minimum reproducible test repo

**Comment by rico345100** [comment]
Same issue here

**Comment by evilebottnawi** [comment]
@rico345100 please create minimum reproducible test repo

**Comment by byzyk** [comment]
Not sure if it's the case for you but I bumped into similar issue and since I'm using TypeScript I had to import images as:

`import * as image from './image.svg';`

@evilebottnawi do you think we should add a note about this in docs?

**Comment by evilebottnawi** [comment]
@byzyk maybe, or maybe we should use `export` and `import` in loader to avoid problem

**Comment by evilebottnawi** [comment]
Also we think about union `url-loader` and `file-loader` (new option base64) to avoid duplicate loaders in same logic

**Comment by evilebottnawi** [comment]
We need implement `export default` for `file-loader` to avoid this problem, will be done for `webpack@5`, now we can't change this because it can break many builds, sorry
