### ISSUE TITLE
publicPath not handled correctly?

### ISSUE THREAD

**Issue by chrisckc** [webpack-contrib/url-loader#164]
Referring to my comment here:
https://github.com/webpack-contrib/file-loader/issues/286

The issue also occurs with url-loader and requires options.publicPath to be set to the same path that is specified in the webpack publicPath property.

The issue is related to the handling of trailing slash in publicPath, caused by the lack of one.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo and describe what you have and what you expected

**Comment by chrisckc** [comment]
No problem, ill update one of my demo repo's to reproduce the issue.

**Comment by evilebottnawi** [comment]
@chrisckc thanks, wait

**Comment by chrisckc** [comment]
Here is a repo is have updated with a new branch:
https://github.com/chrisckc/aurelia-cli-skeleton-typescript-webpack/tree/webpack-publicPath-example

checkout the 'webpack-publicPath-example' branch and run it using:
`npm start -- webpack.server.extractCss`

visit "http://localhost:8080/app"

In the Chrome inspector > sources, find /app/vendor.font-awesome.xxxxxx.chunk.css
notice 'src: url...' entries in lines 9 and 10, 'app' is concatenated with the filename where it should use the '/' path separator.
The woff and woff2 files are loaded by 'url-loader', the eot file is loader by 'file-loader' which has the same issue.

To fix it, edit the webpack.conf.js line 23, add a trailing slash to the baseUrl that is used to populate the output.publicPath `const baseUrl = '/app/';` 

Visiting the same url but with the trailing slash "http://localhost:8080/app/" shows that the issue has gone away. Notice the correct filenames referenced in the font-awesome css.
Font awesome is imported in src/main.ts as a css file so it's not using the sass loader.

It can also be fixed by setting the publicPath property inside url-loader and file-loader to the baseUrl constant, which does seem to make any sense as url-loader must already be inheriting the output.publicPath setting by default.

Also note that the recommendation in the webpack docs is to use a trialing slash for public path:

>The value of the option is prefixed to every URL created by the runtime or loaders. Because of this the value of this option ends with / in most cases.
https://webpack.js.org/configuration/output/#output-publicpath

>Make sure devServer.publicPath always starts and ends with a forward slash.
https://webpack.js.org/configuration/dev-server/#devserver-publicpath-

However it does not cause a problem with the other loaders so still worth looking at.

**Comment by evilebottnawi** [comment]
@chrisckc looks problem related to `file-loader`, `url-loader` just return `base64`

**Comment by chrisckc** [comment]
are you referring to this line?
`{ test: /\.(png|gif|jpg|cur)$/i, loader: 'url-loader', options: { limit: 8192 } },`

I deliberately included and image that was bigger than 8k (pnggradHDrgba.png) to demonstrate the issue.

Notice that the png file name has 'app' prepended to the filename without the path separator and appears outside fo the app dir when looking at the sources in the chrome inspector. The same is also true for the woff2 file.

Adding `publicPath: baseURL` to the options configuration of url-loader in the above mentioned line fixes the issue for the png file. The issue with woff file is fixed by adding it to the other url-loader entry.

**Comment by evilebottnawi** [comment]
@chrisckc I can't understand you problem, you miss option and get unexpected result, where is bug?

**Comment by evilebottnawi** [comment]
@chrisckc let's close issue here
