### ISSUE TITLE
File-Loader 3.0.0 incompatible with this package

### ISSUE THREAD

**Issue by Aghassi** [webpack-contrib/url-loader#167]
https://github.com/webpack-contrib/url-loader/blob/16bc97c17dd20728066dba1b57d3755cf592697d/package.json#L67

With regard to https://github.com/webpack-contrib/url-loader/pull/156, the latest version of `file-loader` is not backwards compatible with this package. I know it is specified as a dependency for `1.x.x` and above. I've been using 2.0.0 just fine as a peer dependency. However, the latest version released today (3.0.0) fails with the following:

```
ValidationError: File Loader Invalid Options

options should NOT have additional properties
```

Is there a reason this package must use 1.x.x? Can there be a peer dependency that specifies the version range so that folks know what they need to run this?

**Comment by evilebottnawi** [comment]
@Aghassi bug in `file-loader` and already fixed in master

**Comment by evilebottnawi** [comment]
Release will be in near future
