### ISSUE TITLE
Compatibility with file-loader 3.0.0

### ISSUE THREAD

**Issue by bukharov** [webpack-contrib/url-loader#168]
Version `1.1.2` when used with `file-loader` version `3.0.0` causes the following failure:

> Module build failed (from ./node_modules/url-loader/dist/cjs.js):
>     ValidationError: File Loader Invalid Options    
>     options should NOT have additional properties    
>         at validateOptions (node_modules/schema-utils/src/validateOptions.js:32:11)
>         at Object.loader (node_modules/file-loader/dist/index.js:21:28)
>         at Object.loader (node_modules/url-loader/dist/index.js:76:19)
> 

I believe that's because `url-loader` passes down its own options to `file-loader`. In my case removing `limit: 8192` from `options` fixed the issue.

**Comment by evilebottnawi** [comment]
Already fixed in master and release will be near future

**Comment by fwh1990** [comment]
At version 5.x, url-loader is using `esModules` however file-loader is using `esModule`. Is that a mistake or something else?

**Comment by fwh1990** [comment]
Here is the commit from file-loader [9eada2d06](https://github.com/webpack-contrib/file-loader/commit/31d6589b71b471f83908e80380dff9b9eada2d06)

**Comment by evilebottnawi** [comment]
@fwh1990 i am working on new major release for url-loader, they will have `esModule` option
