### ISSUE TITLE
Double running loader

### ISSUE THREAD

**Issue by andresmrm** [webpack-contrib/url-loader#17]
Hello! And thanks for this loader (and Webpack)! But I'm having a problem...
It seems to run twice when I do a `require('url!../assets/imgs/file.png')` from a JS file. So the second run is reencoding the encoded Buffer from the first run. In the end, I guess the string accessible in the Browser is not the encoded image, but the encoded module with the encoded image...
Am I doing anything wrong?

For now, I solved the problem adding something like this line in the loader:

```
if (content.toString().slice(0,16) == 'module.exports =') return content
```

**Comment by defrex** [comment]
I'm having this same issue. 

@andresmrm were you able to resolve it?

**Comment by defrex** [comment]
To provide some more context. 

With this loader config

```JS
{ test: /\.svg/, loader: `url?mimetype=image/svg+xml&name=[name]-[hash].[ext]` }
```

`import logo from './logo.svg';` produces the file `logo-33f58a0735f17635fc36f58023b72dcb.svg` during the build, which is correct. However, `<img src={logo}/>` becomes 
```html
<img src="data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJsb2dvLTMzZjU4YTA3MzVmMTc2MzVmYzM2ZjU4MDIzYjcyZGNiLnN2ZyI=" data-reactid=".v103i58mbk.1.0.0.0">
```

That data URI turns out to be this

```js
module.exports = __webpack_public_path__ + "logo-33f58a0735f17635fc36f58023b72dcb.svg"
```

Which of course, isn't a valid SVG file. I'm not sure why. :/

**Comment by andresmrm** [comment]
Hi, @defrex ! I changed the loader code to [this](https://gist.github.com/andresmrm/dbf24a1caeaf0383cb0a#file-gistfile1-txt-L12). And then I use it like this:

    const assets = {
        logo: require('url?once=1!../assets/logo.svg'),
        ...
    }

And then, set my `img` `src` to `assets.logo`

It's an ugly hack, but seems to work here...

**Comment by defrex** [comment]
That worked for me as well.

Though, it lead me to look more into why the asset was being loaded twice. Looks like it was matching my SVG loader and my normal image loader. Once I fixed the regex for the image loader the problem went away and I was able to remove the patch.

Perhaps your issue is similar?

**Comment by andresmrm** [comment]
I'm glad it was helpfull for you. =)
But it seems not to be my case, since I'm not loading the images in the webpack loader, only in a JS file.

**Comment by michael-ciniawsky** [comment]
@andresmrm Still got this regression, I would like to hear more about this if possible 😛

**Comment by andresmrm** [comment]
Hello, @michael-ciniawsky!

I tested my code now without using my custom modification for url loader, and it seems to work. So I'm changing back to it. Thanks for reaching me! Feel free to close this issue.

**Comment by michael-ciniawsky** [comment]
@andresmrm If you think there is an issue regarding `url-loader` + reasonable configuration just open a new issue 😛

**Comment by xuxinhang** [comment]
I meat the same issue just now.
The problem was solved when I add `/\.svg$/` to the `exclude` prop  of the rule using `file-loader`.
That show the issue would appear when a file type was processed by `file-loader` and `url-loader` at the same time.
