### ISSUE TITLE
Mp3 Files URL-Loader still dont work

### ISSUE THREAD

**Issue by liamcharmer** [webpack-contrib/url-loader#170]
* Operating System: Mac OS
* Node Version: ?
* NPM Version:?
* webpack Version:?
* url-loader Version:?

### Expected Behavior

For the webpack to build

### Actual Behavior

ERROR in ./assets/sounds/rain-bg.mp3 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.

### Code

```js
  // webpack.config.js
  // If your bitchin' code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?
 config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          
          exclude: /(node_modules)/,

        }),
         config.module.rules.push({
            test: /\.(ogg|mp3|wav)$/i,
            loader: 'file-loader'
          })

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
