### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by moon-deer** [webpack-contrib/url-loader#173]
Hey guys. I've got this kind of warning just now.

* Operating System: macos mojave 10.14.2 (18C54)
* Node Version: v11.9.0
* NPM Version: 6.5.0
* webpack Version: 4.29.0
* url-loader Version: 1.1.2
* Yarn Version: 1.13.0

### Actual Behavior

> warning " > url-loader@1.1.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".

### How Do We Reproduce?

> yarn add url-loader --dev

In the package.json of this plugin we have:
> "peerDependencies": { "webpack": "^3.0.0 || ^4.0.0" },

**Comment by evilebottnawi** [comment]
@moon-deer you need install webpack

**Comment by moon-deer** [comment]
> @moon-deer you need install webpack

It'a actually installed and it's version mentioned in the description

**Comment by evilebottnawi** [comment]
@moon-deer npm don't lie, if you don't install webpack npm says what you need install, double check, maybe you have global installed version

**Comment by chibicode** [comment]
@evilebottnawi shouldn't `peerDependencies` be `^4.0` instead of `^4.0.0`? Any `4.x` version should work.

https://github.com/webpack-contrib/url-loader/blob/master/package.json#L37

**Comment by TylerJNewman** [comment]
I am having the same issue....

  "name": "webpack",
  "version": "4.41.2",
