### ISSUE TITLE
Needs charset to render base64 as src

### ISSUE THREAD

**Issue by mAAdhaTTah** [webpack-contrib/url-loader#174]
* Operating System: OSX
* Node Version: 11.9
* NPM Version: 6.4.0
* webpack Version: 4
* url-loader Version: 1.1.2

### Expected Behavior

Display the base64-encoded image in the `src` attribute.

### Actual Behavior

Image doesn't display properly in Chrome.  Adding this makes the image display properly: `src={logo.replace('base64,', 'charset=utf-8;base64,')}`. It needs the charset bit to work.

### How Do We Reproduce?

```js
import logo from './logo.png';

<img src={logo.replace('base64,', 'charset=utf-8;base64,')} />
```

**Comment by evilebottnawi** [comment]
Image is binary, no need set charset please create minimum reproducible test repo

**Comment by mAAdhaTTah** [comment]
Hmmm, dunno what happened there tbh, coulda been a caching issue on my end, but I can't reproduce anymore. Sorry!
