### ISSUE TITLE
about url-loader limit config

### ISSUE THREAD

**Issue by Titans1001** [webpack-contrib/url-loader#175]
The value of limit in the configuration cannot be set to 0 or anything that appears to be false will go as default，so when we don't need base64 encoding, we usually set the limit value to 0 and it won't work，We can only set the limit to a number if it is true。Can you change the source code so that 0 is also a value that can be set to work。
### Code
  code:
     {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 1,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      }

**Comment by evilebottnawi** [comment]
Please use issue template in future, yes we can do it, feel free to send a PR

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/url-loader/pull/180
