### ISSUE TITLE
Animated GIF not created

### ISSUE THREAD

**Issue by SetTrend** [webpack-contrib/url-loader#178]
### Synopsis

`url-loader` doesn't create valid animated GIF.

### System Data

* Operating System: Windows 10x64
* Node Version: v10.15.3
* NPM Version: 6.4.1
* webpack Version: 4.29.6
* url-loader Version: 1.1.2

### Expected Behavior

The following animated GIF should be rendered by the browser using a `data:` URL created by `url-loader`:

![InlineThrobber](https://user-images.githubusercontent.com/9283914/55327032-76afdb80-5489-11e9-94bc-a2e9ace4663b.gif)

### Actual Behavior

The following, incorrect/invalid, `data:` URL is being created:

```
url(data:image/gif;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvSW5saW5lVGhyb2JiZXIuZ2lmIjs=)
```

Which in turn, when decoded, results in:

```js
> atob("bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvSW5saW5lVGhyb2JiZXIuZ2lmIjs=")

'module.exports = __webpack_public_path__ + "images/InlineThrobber.gif";'
```

#### webpack.config.js

```js
const path = require('path');

const cleanWP = require('clean-webpack-plugin').default;

module.exports = {
  entry: {
    testIncrementalSearchWC: "./app/components/_mock/incremental-search/page",
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/i,
        use: 'ts-loader',
        exclude: [
          /[/\\]node_modules[/\\]/,
          /[/\\].*\.js/]
      },
      {
        test: /\.scss$/i,
        use: [{
          loader: 'style-loader' // creates style nodes from JS strings
        }, {
          loader: 'css-loader' // translates CSS into CommonJS
        }, {
          loader: 'sass-loader' // compiles SASS to CSS
        }]
      },
      {
        test: /\.(png)|(svg)|(je?pg)|(gif)$/i,
        use: 'url-loader',
        issuer: {
          include: /app[/\\]components[/\\].*\.(ts)|(scss)$/
        }
      },
      {
        test: /\.(png)|(svg)|(je?pg)|(gif)$/i,
        use: {
          loader: 'file-loader',
          options: {
            outputPath: 'images',
            name: "[name].[ext]"
          }
        },
        issuer: {
          include: /scripts[/\\]function[/\\].*\.(ts)|(scss)$/
        }
      }
    ]
  },
  resolve: {
    extensions: [".ts", ".js", ".scss"]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.join(__dirname, 'dist'),
    publicPath: "/dist/"
  }
};
```

#### Screenshots depicting the path information:

![url-loader-1](https://user-images.githubusercontent.com/9283914/55327180-d312fb00-5489-11e9-9413-c7b9db70ae4b.png)

![url-loader-2](https://user-images.githubusercontent.com/9283914/55327186-d4dcbe80-5489-11e9-85a0-94d576477619.png)

![url-loader-3](https://user-images.githubusercontent.com/9283914/55327191-d6a68200-5489-11e9-8608-fcb52c3a7d9a.png)

### How Do We Reproduce?

1. Recreate the depicted folder structure (presumably not required)
1. Create a SASS file, referencing an animated GIF
1. Create some TypeScript file, creating an element that's addressed by the above SASS file
1. Copy above `webpack.config.js` file

**Comment by evilebottnawi** [comment]
We don't modify content, maybe something wrong in your configuration, can you create minimum reproducable test repo

**Comment by SetTrend** [comment]
I'm not sure...

`file-loader` exhibits the same issue. Using `file-loader`, webpack copies the graphics file to the `dist` folder and scrambles the destination file, too.

I guess it must have to do with how `webpack` copies files to the `dist` folder.

**Comment by SetTrend** [comment]
Further investigation showed, that when using a `PNG` file, `file-loader` creates the correct PNG file (which it doesn't with the generated animated GIF), whereas `webpack-dev-server` and `url-loader` still yield a defective `data:` URL:

```
url(data:image/png;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvYXJyb3dfZG93bl9ibHVlXzE2LnBuZyI7)
```
... resulting in:
```
> atob("bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvYXJyb3dfZG93bl9ibHVlXzE2LnBuZyI7")

'module.exports = __webpack_public_path__ + "images/arrow_down_blue_16.png";'
```

**Comment by SetTrend** [comment]
As mentioned in my first post, the image URLs are taken from a SASS file.

Probably the `sass-loader` > `css-loader` > `style-loader` chain is causing the faulty result.

**Comment by SetTrend** [comment]
Hi @evilebottnawi :

I'm not sure which of the number of loaders involved causes this issue, or if it's even webpack itself. You closed my other thread. Do you believe this repository is the right place to get this issue solved? Or which repository would you suggest to file this issue?

Do you still want me to create a repository or can you reproduce this issue with the information given?

**Comment by SetTrend** [comment]
After having had one night of sleep and doing some more testing I can now confirm that the issue boils down to any of the webpack loaders inserting the JavaScript statement `module.exports = __webpack_public_path__ + "images/InlineThrobber.gif";` instead of the resolved expression `/dist/images/InlineThrobber.gif` into the CSS style rules:

![image](https://user-images.githubusercontent.com/9283914/55390388-65250d00-5537-11e9-8803-c5ecd3d23013.png)

**Comment by SetTrend** [comment]
OK, after some more research, here's the part in webpack.config.js that's causing the trouble (I altered the paths to ease the supposed intention):

```js
{
  test: /\.(png)|(svg)|(je?pg)|(gif)$/i,
  use: 'url-loader',
  issuer: {
    include: /web[/\\]components[/\\].*\.(ts)|(scss)$/
  }
},
{
  test: /\.(png)|(svg)|(je?pg)|(gif)$/i,
  use: {
    loader: 'file-loader',
    options: {
      outputPath: 'images',
      name: "[name].[ext]"
    }
  },
  issuer: {
    include: /app[/\\]function[/\\].*\.(ts)|(scss)$/
  }
}
```

The web components' images are supposed to be embedded in the minified chunks, so these chunks can be deployed to other clients. That's what the first rule is about.

The second rule defines the rules for a first client utilizing the above mentioned web components. The client's custom elements are supposed to share their images in the `/dist/images` folder.

One of the client's custom components (rule # 2) utilizes (aka `import`s) one of the above mentioned web components (rule # 1). This is causing rule #2 to erroneously be applied to the web components (rule # 1), too:

Not only are the web components' images saved to `/dist/img`, the SASS files' `url()` is erroneously output with JavaScript code instead of the images' data URL.

**Comment by evilebottnawi** [comment]
Please don't spam here, minimum reproducible test repo is enough, it is open source, not your personal help

**Comment by SetTrend** [comment]
@evilebottnawi: I'm not spamming. I'm trying to give enough information for contributors to fix this issue. Nothing more.

**Comment by evilebottnawi** [comment]
@SetTrend we are not doing anything supernatural here, just convert buffer to `data:`, can you create minimum reproducible test repo?

**Comment by SetTrend** [comment]
Thanks, @evilebottnawi 👍 

Sure. I'll be glad to. Please allow me a day to set this up. I'll do this after hours.

**Comment by SetTrend** [comment]
@evilebottnawi:

Here's there repository you requested:

[/SetTrend/webpack-issue](https://github.com/SetTrend/webpack-issue)

**Comment by evilebottnawi** [comment]
Here problem in configuration:
1. Both loader were used - `url-loader` and `file-loader` due invalid configuration so image was broken (you can comment `file-loader` and see all works fine). Problem in `issuer.include` configuration (broken regexp) because using:
```
issuer: {
  include: /inner-wc-styles\.scss$/
}
```
and
```
issuer: {
  include: /outer-wc-styles\.scss$/
}
```

fix problem with broken images for `url-loader`.

2. Second problem in `publicPath` option, you need setup:
```
output: {
  filename: "[name].bundle.js",
  path: path.join(__dirname, 'dist'),
  publicPath: "/dist/"
},
```

**Comment by SetTrend** [comment]
@evilebottnawi :

In your solution you're giving a fixed string as a regex. That's not something we can use.

Why do you believe there is an issue with these regular expressions:

```
/src[/\\]inner[/\\].*\.(ts)|(scss)$/
/src[/\\]outer[/\\].*\.(ts)|(scss)$/
```

They are both valid and distinctive. I don't believe they are the reason for this issue to break,

Strange enough, the image file got copied to the correct directory when I used:

```json
"devServer":
{
  "publicPath": "/dist/"
}
```

instead of

```json
"output":
{
  "publicPath": "/dist/"
}
```

Though, I comprehend that putting the path to `output.publicPath` is the right solution.

**Comment by evilebottnawi** [comment]
> Why do you believe there is an issue with these regular expressions:

Try to avoid `src`, you can debug webpack and see what is issuer in this place.

> Strange enough, the image file got copied to the correct directory when I used:
I already open issue in `webpack-dev-server`

**Comment by SetTrend** [comment]
@evilebottnawi 👍

I couldn't find a "build" script in the Webpack project and the `readme` doesn't get clear on how to build (and debug) Webpack. Can you help me and point to the right direction?

**Comment by tamelbrun** [comment]
@SetTrend 
You might be interested to learn that we had a very similar issue with `url-loader`, which I managed to trace to `webpack` automatically adding `url-loader` by default. This caused `url-loader` to be called twice for the same file, feeding the output of the first call to the second. Obviously, this did not result in a valid data URL for the image. I'm not sure if this is a bug or a "feature" in `webpack`.
