### ISSUE TITLE
Corrupted or not proceed image matched multiple module rule simultaneously

### ISSUE THREAD

**Issue by domino2** [webpack-contrib/url-loader#188]
- Operating System: Mac Mojave 10.14.6
- Node Version: 10.14.0
- NPM Version: 6.11.2
- webpack Version: 4.39.2
- url-loader Version: 2.1.0

Also tested with Docker image lambci/lambda:build-nodejs10.x

### Expected Behavior

When having multiple module rules matching the image asset with different name location, the image will appear in the build folder under specific paths (name) multiple times.

### Actual Behavior

With more roles with same test to match same image type,
just the last image is proceed as it should to, 
some roles are ignored (when having 5, just 3 are proceed) and
all non last images are corrupted (blank images).

### Code

```js
module: {
  rules: [
    {
      test: /\.png$/,
      loader: require.resolve('url-loader'),
      options: {
          limit: 100,
          name: 'static/assets1/images/[name].[hash:8].[ext]'
      }
    },
    {
      test: /\.png$/,
      loader: require.resolve('url-loader'),
      options: {
          limit: 100,
          name: 'static/assets2/images/[name].[hash:8].[ext]'
      }
    },
    {
      test: /\.png$/,
      loader: require.resolve('url-loader'),
      options: {
          limit: 100,
          name: 'static/assets3/images/[name].[hash:8].[ext]'
      }
    },
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: "babel-loader"
    }
  ]
}
```

### How Do We Reproduce?

Use same already used rule upon asset image with different name-location or
fetch the [sample repo - webpack-img-loader-issue](https://github.com/domino2/webpack-img-loader-issue) to present the issue.

**Comment by evilebottnawi** [comment]
It si expected, you should not use loader twice on same assets, you can use `include`/`exclude` to filter them

**Comment by domino2** [comment]
Sorry, but I disagree. 
I figured out that fact what you just said, but it took a time as the current behavior is clunky.

Based on the fact that in case of use the `url-loader` three times, one image is passed, second is ignored and last is just blank. So definitelly not consistent behaviour.

As a developer I'm expecting that if I'm using `url-loader` wrongly, the exception will appear in the console inform me or another better behaviour is to allow this use case as it is not restricted by webpack either.
