### ISSUE TITLE
How can i use name function with url-loader?

### ISSUE THREAD

**Issue by pasBone** [webpack-contrib/url-loader#190]
- Operating System:
- Node Version:  v10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.28.4
- url-loader Version: 0.6.2

### Feature Use Case

file-loader screenshot:
![image](https://user-images.githubusercontent.com/18027183/64473486-26584a80-d19a-11e9-9eba-5cdc2ba80f33.png)

url-loader screenshot:
name function not work.
![image](https://user-images.githubusercontent.com/18027183/64473500-50aa0800-d19a-11e9-96f2-43bbe45cfcca.png)

How can i use name function with url-loader?

thank you!

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions, i don't know what is boilerplates you are use, open issue in your boilerplate
