### ISSUE TITLE
Limit option does not support 'Infinity' or 'Max Value'

### ISSUE THREAD

**Issue by threequartersjohn** [webpack-contrib/url-loader#191]
Hello, 

I'm trying to use url-loader to juggle between files that should be translated and not, and using `Infinity` or `Number.MAX_VALUE` would be a nice way to implement a default limit. 

- Operating System: macOS Mojave 10.14.5
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.0
- url-loader Version: 2.1.0

### Expected Behavior

Using `Infinity` or `Number.MAX_VALUE` in `limit` option should, respectively, load all files, or load all files with file size below the maximum integer.

### Actual Behavior

When using either of those values, the files are not translated and are passed to file-loader instead, regardless of their size

### Code

```js
module: {
    rules: [
        {
            test: /\.svg$/,
            loader: 'url-loader',
            options: {
                limit: Number.MAX_VALUE, // Will not work, and fallback will be used
            },
        },
    ],
},
```

### How Do We Reproduce?

Attempting to load any file and putting `Infinity` or `Number.MAX_VALUE` in the limit option of the loader.

Some experimentation has revealed that this is caused by using `parseInt()` when the `typeof limit` is a number, as the current implementation will do so whether the limit if a string or a number. If you'd be interested i'd be willing to make a PR to handle this.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by evilebottnawi** [comment]
Fixed in master, release in near future
