### ISSUE TITLE
url-loader@1.1.1 requires a peer of webpack@^4.0.0 but webpack@2.7.0 was installed

### ISSUE THREAD

**Issue by felibq** [webpack-contrib/url-loader#197]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

**Comment by felibq** [comment]
but I cant use webpack by 4.0.0, how to solve it.

**Comment by evilebottnawi** [comment]
Use old version, anyway i strongly recommend update webpack to latest version
