### ISSUE TITLE
Allow expressing limit as a function

### ISSUE THREAD

**Issue by almstrand** [webpack-contrib/url-loader#199]
- Operating System: MacOS 10.15
- Node Version: v10.17.0
- NPM Version: 6.11.3
- webpack Version: 4.41.2
- url-loader Version: 3.0.0

### Feature Proposal

There are scenarios where developers may want more control over which files are loaded as data URIs vs. stored/referenced as separate files. However, the current implementation applies a global limit that causes the same rule to be applied across all files.

### Feature Use Case

A common scenario is server-side-rendered and progressive web applications that wish to render an initial page with a low-resolution image. To enable prompt rendering upon downloading the first HTML document, applications may benefit from displaying images loaded via data URIs. Setting a global limit can enable this scenario however a global limit also causes other images in the application to become stored as data URIs, provided their size falls below the limit. This may be an undesired behavior.

Another common scenario where developers may wish to limit which files are converted to data URIs is when CSS media queries are used to render one among many images, depending on the browser window dimensions or other factors. Assuming all such images have a size that is less than the global limit, all images will be stored as data URIs and will unnecessarily, sometimes significantly, inflate the JS bundle size.

**Comment by evilebottnawi** [comment]
Thanks, it is unnecessary because you can use this syntax:
```js
import url from '!url-loader?limit=123!./file.png';
```

**Comment by almstrand** [comment]
That's great to know, thanks!  That said I think there can be scenarios where that ☝️syntax can be quite verbose and tedious. For example, package [`next-images`](https://github.com/twopluszero/next-images) uses `url-loader` to enable loading images in Next.js projects, and configures `url-loader` with several parameters. If those parameters are passed using the syntax it could look like this:
```
require('!url-loader?limit=0&publicPath=/_next/static/images/&outputPath=static/images/
&name=[name]-[hash].[ext]!./images/placeholder-400-low-quality.png');
```
In image-heavy applications (and again considering bloat from media queries, `<source/>` elements, etc) this syntax can contribute to code becoming less readable. With this PR, the above could be replaced with:
```
require('/images/placeholder-400-low-quality.png?limit=0');
```
That said, I believe the syntax does address the majority of the concerns raised, so I feel we can close this issue.
