### ISSUE TITLE
Why url-loader stop supporting nodejs 8?, as webpack 5 still supporting nodejs 8 and higher?

### ISSUE THREAD

**Issue by smondal** [webpack-contrib/url-loader#203]
In the webpack 5 documentation its mention that  webpack still supporting nodejs 8 and higher, then why url-loader stop supporting nodejs 8. Is there any specific reason?
https://github.com/webpack-contrib/url-loader/blob/master/package.json#L16
https://webpack.js.org/concepts/

**Comment by anikethsaha** [comment]
node v8 will be depreciated soon this year. maybe in Jan itself.
I am pretty sure webpack will drop the support as well.

**Comment by smondal** [comment]
Thanks @anikethsaha

**Comment by sokra** [comment]
> I am pretty sure webpack will drop the support as well.

We did. It's now >= 10

**Comment by smondal** [comment]
So we need to change all the loader and plugin dependencies >=10

**Comment by anikethsaha** [comment]
yes.... 10x is the current LTS. it should be changed 👍

**Comment by evilebottnawi** [comment]
Thanks for issue, answer above
