### ISSUE TITLE
Usage with require.context?

### ISSUE THREAD

**Issue by ZebraFlesh** [webpack-contrib/url-loader#206]
Documentation Is:

- [ ] Missing
- [X] Needed
- [ ] Confusing
- [X] Not Sure?

### Please Explain in Detail...
After upgrading to the 3.0 release with `esModule` defaulting to `true`, I had some code break. Given a loader config of:
```
const configureImageLoader = (isServer) => ({
  test: /\.(jpg|jpeg|png|gif|webp|svg)$/,
  use: {
    loader: 'url-loader',
    options: {
      outputPath: 'images',      
      limit: 8192,
      emitFile: !isServer
    }
  }
});

...

  config: {

    ...

    module: {
      rules: [
        configureImageLoader(isServer)
      ]
    }
  }
```

This code stopped working:
```
function mapImages(context) {
  const imageNames = context.keys();
  const imagePaths = imageNames.map(context);
  const imageMap = new Map();
  for (let i = 0; i < imageNames.length; i++) {
    imageMap.set(imageNames[i].slice(2), imagePaths[i]);
  }
  return imageMap;
}

...

const images = mapImages(require.context('./images', false, /\.png$/));
```

The fix seemed easy enough. When creating the Map, change
```
 imageMap.set(imageNames[i].slice(2), imagePaths[i]);
```
to
```
 imageMap.set(imageNames[i].slice(2), imagePaths[I].default);
```

This makes sense to me because I'm now dealing with ES modules instead of the CommonJS format. If what I want is the 

### Your Proposal for Changes
Is a usage of Webpack's `require.context` interesting enough to warrant additional documentation? Or would you consider this "obvious"? (It took me a little figuring out/debugging before a lightbulb went off.) Maybe this issue is enough for folks to find their way?

**Comment by evilebottnawi** [comment]
It is expected because we use ES modules, you can use `imagePaths[I].__esModule ? imagePaths[I].dfault : imagePaths[I]`,  it works the same for all modules, not only for url-loader, `babel` do same https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs, if you think we should documented that, please open issue https://github.com/webpack/webpack.js.org here, because it is not only for url-loader
