### ISSUE TITLE
Blob Url Support

### ISSUE THREAD

**Issue by franleplant** [webpack-contrib/url-loader#211]
- Operating System: any supported
- Node Version: any supported
- NPM Version: any supported
- webpack Version: 4.x
- url-loader Version: latest

### Feature Proposal

I see that this lib converts the files into data URIs but I was just reading about Blob Urls and I was wondering if you considered as a possible solution to inlining files.

I read somewhere that Blob Urls are created from binary data which means that we don't have to cope with the 30% size overhead of Data URIs but we do need to do some further logic to converting binaries into Blob Urls and when to reject them.

Ref: https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used

I haven't tried this but the basic workflow I have in mind is something like this

- statically the loader will inline files into [ArrayBuffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)
- at runtime (this solution requires a runtime) we will create Blob Urls
- export the blob urls from the module
- revoke them eventually? Im not sure we really need to

```
// compiled version of file.jpg
const binary = createArrayBufferFromFile(file.jpg)
const blobUrl = URL.createObjectURL(binary)
module.exports = blobUrl
```

### Feature Use Case

The same as the main use case of this lib but with a perf boost

Cheers!

**Comment by evilebottnawi** [comment]
My recommendation is to create own loader, url-loader has compatibility with JS/CSS/HTML and other default web standards, blob supported only for JS, so better to implement own loader for that
