### ISSUE TITLE
Images not inlined in Svelte 3 app

### ISSUE THREAD

**Issue by rraallvv** [webpack-contrib/url-loader#214]
- Operating System:
macOS 10.15.2
- Node Version:
11.15.0
- NPM Version:
6.7.0
- webpack Version:
4.38.0
- url-loader Version:
4.1.0

### Expected Behavior

```
<img src="./assets/logo.png">
```
Should be converted in the output to something like this:
```
<img src="data:image/png;base64,iVBOR…A/zkqwGTTPH9AAAAAElFTkSuQmCC">
```

### Actual Behavior

All image tags in all components are not inlined no matter their size in disk. 

### Code

```js
// webpack.config.js
module: {
  rules: [
    //...
    {
      test: /logo.png/,
      loader: (process.stdout.write("!!!\n"), 'url-loader')
    }
```

### How Do We Reproduce?

Clone [this repository](https://github.com/rraallvv/spark-payments-nimiq-webpack) and the rule to make `url-loader` inline all images to `webpack.config.js` then build the output with the command `npm run start`, after the app opens on the browser check the source code for the image at the top like this:

![Screen Shot 2020-06-12 at 4 18 57 PM](https://user-images.githubusercontent.com/1840524/84543198-e134ec00-acc8-11ea-9d38-2a5d4f1a69f1.png)

**Comment by evilebottnawi** [comment]
Please open an issue for `svelte-loader`, no problem on `url-loader` side, `svetle-loader` handles `svetle` template
