### ISSUE TITLE
DataURL images also send network request to public path

### ISSUE THREAD

**Issue by marinav** [webpack-contrib/url-loader#217]
- Operating System: Mac OSX
- Node Version: 12.16.2
- NPM Version: 6.14.4
- webpack Version: 4.42.1
- url-loader Version: 4.1.0

### Expected Behavior

Images under 1000 bytes are inlined as DataURL and no network request are done for those images.

### Actual Behavior

Images under 1000 bytes are inlined as DataURL but **a network request is done for each images** (and failing with 404 error code because path doesn't exists).

Here a screenshot in local mode : 

![Capture d’écran 2020-07-15 à 18 33 01](https://user-images.githubusercontent.com/4086197/87571010-b7a52100-c6c9-11ea-8a41-d77a4b4af8ec.png)

### Code

My webpack images loader settings
```js
{
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.svg$/],
            use: [
              {
                loader: require.resolve('url-loader'),
                options: {
                  limit: 10000,
                  name: 'static/media/[name].[hash:8].[ext]',
                }
              },
              {
                loader: require.resolve('image-webpack-loader'),
                options: {
                  optipng: {
                    enabled: false,
                  },
                  svgo: {
                    enabled: false
                  },
                  webp: {
                    quality: 85
                  }
                }
              }
            ]
}
```
The way I import images in my views
```js
import CloseIcon from '../../../assets/images/icons/close.svg';

<img src={CloseIcon} alt='close' />
```

### How Do We Reproduce?

I think the best way is creating a CRA app and eject (what I did 2 years ago), and putting my[ webpack config file](https://playcode.io/636361)

I have this problem in production and to reproduce it in local you have to run

`yarn build`
`yarn serve`

**Comment by evilebottnawi** [comment]
Because some images is more than `limit: 10000`

**Comment by evilebottnawi** [comment]
From docs:
```
If the file size is equal or greater than the limit file-loader will be used (by default) and all query parameters are passed to it.
```

**Comment by evilebottnawi** [comment]
> Images under 1000 bytes are inlined as DataURL but a network request is done for each images (and failing with 404 error code because path doesn't exists).

We don't inject network request, you can look at our code :smile:

**Comment by marinav** [comment]
> Because some images is more than `limit: 10000`



> From docs:
> 
> ```
> If the file size is equal or greater than the limit file-loader will be used (by default) and all query parameters are passed to it.
> ```

Yes I know and it's working well, images size greater than limit are loaded via path, but images under limit are inlined as DataURL but still do a network request...I know you don't inject network request according to the doc but I don't understand why I still have one...

I thought it could be some cache but I have nothing about those images in asset-manifest, or maybe the way I import images ? Or something that I do wrong in the webpack configuration...?

Thanks for your time 🙏

**Comment by marinav** [comment]
You can see here screenshots from my production app :

A first call with path 404 (type is text/html)
<img width="539" alt="Capture d’écran 2020-07-16 à 10 15 23" src="https://user-images.githubusercontent.com/4086197/87645091-4eff8800-c74d-11ea-8c00-8fb06ea7422c.png">

And then correct call  as DataURL (type svg+xml)
<img width="535" alt="Capture d’écran 2020-07-16 à 10 15 17" src="https://user-images.githubusercontent.com/4086197/87645097-5030b500-c74d-11ea-8450-74efb13e2de9.png">

**Comment by evilebottnawi** [comment]
@marinav Can you create reproducible test repo?

**Comment by marinav** [comment]
@evilebottnawi ok I'm sorry it was due to an SSR setting in my project, I haven't notice before...I close the issue sorry for the waste of time.

Thank you 🙏
