### ISSUE TITLE
Different default limit values in documentation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpack-contrib/url-loader#223]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In README.md, the big table of options lists `true` as the default value for `limit`. Just after the table, the section for specifically `limit` lists its default as `undefined`.

### Your Proposal for Changes

Pick one and stick with it. :)

**Comment by alexander-akait** [comment]
Because it is default value, all files will be converted to `data:`

**Comment by alexander-akait** [comment]
Oh, I see, sorry

**Comment by alexander-akait** [comment]
Yep, feel free to fix it, default value is `undefined`
