### ISSUE TITLE
otf font not being loaded correctly

### ISSUE THREAD

**Issue by tnrich** [webpack-contrib/url-loader#23]
Here's my config:

```
{
      test: /\.(otf|eot|woff|woff2|ttf|svg|png|jpg)$/,
      loader: 'url-loader?limit=30000&name=[name]-[hash].[ext]'
    }
```

When I require a `.ttf` font everything works fine. Then trying to use `.otf`, no error is thrown, but the font simply doesn't load.

Any help would be greatly appreciated. Thanks!

**Comment by michael-ciniawsky** [comment]
@tnrich Do your still have this issue? I need more info about your setup please

**Comment by tnrich** [comment]
@michael-ciniawsky you can close this for the time being as I'm not currently using url loader and can't get you that info. Thanks for getting back to me though. Good luck!

**Comment by michael-ciniawsky** [comment]
I will ensure to test the common font variants for the next `major` of `url-loader` and if any new regressions just open a new issue 😛

**Comment by tnrich** [comment]
Thanks!
