### ISSUE TITLE
Add ability to set encodings

### ISSUE THREAD

**Issue by kisenka** [webpack-contrib/url-loader#25]
Hi @sokra! 
Thanks for the great loader.

Default loader behaviour is to encode source and return Data URI. But for SVG is [no necessary to encode source](https://css-tricks.com/probably-dont-base64-svg) in base64, because it works with raw content encoded with encodeURIComponent. Moreover it will decrease ~30% of content length and save browser resources for unpacking base64 string. My suggestion is to add user defined handlers to specific mime-type, something like this: 

``` js
{
  module: {
    loaders: [
      {
        test: /\.(jpg|png|gif|svg)$/
        loader: 'url?limit=10000'
      }
    ]
  },
  url: {
    handlers: {
      'image/svg+xml': function (content) {
        return 'data:image/svg+xml,' + encodeURIComponent(content);
      }
    }
  }
}
```

For backward compatibility option can be disabled by default. For details please take a look at my [advanced-url-loader](https://github.com/kisenka/advanced-url-loader) which based on url-loader. I can make a PR, if you agree. Also I want be a volunteer and cover all existing loader code with tests. And close some issues.

**Comment by joekrill** [comment]
IE has issues with Base64 encoded data URIs, so I'm having problems related to this also. But I'm not sure it even needs to be as complicated as you suggest. A simple option to toggle using URL-encoded plaintext instead of Base64 encoding should be sufficient. Those are the only valid way to encode data URIs anyway (see http://codepen.io/tigt/post/optimizing-svgs-in-data-uris). Then you could just do something like:

```
loaders: [{ 
    test: /\.(svg)$/,
    loader: 'url?limit=10000&encoding=url'
}, {
   test: /\.(png)$/,
   loader: 'url?limit=10000&encoding=base64'
}]
```

**Comment by kisenka** [comment]
@joekrill good suggestion

**Comment by michael-ciniawsky** [comment]
@kisenka Sry for the delay are you still interested in a solution here ? @joekrill's comment sounds promising (add options to set encoding)

**Comment by michael-ciniawsky** [comment]
@kisenka @joekrill PR highly welcome after #70 lands 😛

**Comment by michael-ciniawsky** [comment]
#28 needs to be reworked (WIP)
