### ISSUE TITLE
How do you actually include an image?

### ISSUE THREAD

**Issue by zwhitchcox** [webpack-contrib/url-loader#26]
I get that you type `require('image.png')`, but how do you actually put that in your app?

I have tried `<img src={require('image.png')} />` and just plain `{require('image.png')}`, but it doesn't work. I'm running out of idea.

**Comment by zwhitchcox** [comment]
So, now, when I type `<img src={require('./image.png')} />` webpack just dies. This is the error it gives me.

```shell
npm ERR! Linux 3.8.11
npm ERR! argv "/usr/bin/iojs" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! @ start: `webpack-dev-server --hot --inline --history-api-fallback`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'webpack-dev-server --hot --inline --history-api-fallback'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --history-api-fallback
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zane/3ashworth/npm-debug.log
```

**Comment by Sinistralis** [comment]
Using ES6 and JSX, you should be able to do:

`import someVar from 'imgPath'.
<img src={someVar}/>`

**Comment by michael-ciniawsky** [comment]
@zwhitchcox Please provide more info about your setup (`webpack.config.js`). E.g is the `<img src={require('image.png')} />` inside a `.js` or `.html` file (requires another loader) ?

**Comment by zwhitchcox** [comment]
Oh sorry, this was fixed by the previous comment
