### ISSUE TITLE
Relative paths in url() are not resolved correctly for imported files with @import

### ISSUE THREAD

**Issue by ivosabev** [webpack-contrib/url-loader#29]
When you @import a CSS file the relative paths are resolved based on the file I am importing into not relative to the imported file.

**File structure**

```
/assets/background.png
/assets/Layout.css
/component/Header/Header.css

```

**Header.css**

```
@import '../../assets/Layout.css';
```

**Layout.css**

```
body {
  background: url(background.png);
}

```

This throws an error, because for some reason after the import the relative path is no more relative to Layout.css. Any ideas?

**Comment by michael-ciniawsky** [comment]
@ivosabev Can you provide more info about your setup please (`webpack.config.js`) ?

**Comment by ivosabev** [comment]
Unfortunately this was quite some time ago and I don't have the same setup anymore. I guess you may close it since no one else had the same issue.

**Comment by michael-ciniawsky** [comment]
Alright, we are planning to take a through look at `css-loader/url-loader` and friends to shape issues like that out in the future, but that's a abstract statement here. Sry for the delay and inconvience
