### ISSUE TITLE
Using absolute path

### ISSUE THREAD

**Issue by papigers** [webpack-contrib/url-loader#37]
I'm building a react application and using a very "deep" folder structure convention where each component has its own folder and sub components are nested withing those folders. 
I also want to keep all my assets in one folder, is there a way to avoid `require(../../../../logo.png)` and somehow configure it to load images directly from my assets folder?

**Comment by Manidos** [comment]
@papigers, have you found a solution? Having the same problem http://stackoverflow.com/questions/39734132/file-loader-set-root-file-path?noredirect=1&lq=1

**Comment by XylitolLin** [comment]
@Manidos , the page not found and i want to know how to solute that problem

**Comment by papigers** [comment]
Check webpack's `resolve.root` and `resolve.alias` config options.
