### ISSUE TITLE
limit parameter is not working correctly

### ISSUE THREAD

**Issue by liximomo** [webpack-contrib/url-loader#40]
Webpack logged the img size of 13kb, and I have the config:

```
loader: `url?limit=10000&name=img/[name]_[hash].[ext]` 
```

It outputs data-url instead of emitting file.

**Comment by Avien** [comment]
+1

**Comment by michael-ciniawsky** [comment]
@liximomo Still got this regression, I need more info about your setup (`webpack.config.js`) with the relevant parts please. Does it e.g work without specifying the `name` option

**Comment by evilebottnawi** [comment]
@liximomo why your use options in `loader`, for this we should use `options`(`{ loader: 'url-loader', options: { limit: 9000 }}`) or use in `require` (`require('url-loader?limit=20000!shared/images/logo.png');`)

/cc @michael-ciniawsky maybe it is old webpack behavior?
