### ISSUE TITLE
Confused how this would ever work with a physical file (limit on)

### ISSUE THREAD

**Issue by DominicTobias** [webpack-contrib/url-loader#48]
Hi, thanks for this plugin. It works if I use it in combination with ExtractTextPlugin, where the urls get re-written on output.

However if it's using the normal blobs, then the paths in the blobs don't get re-written.

For example in a node_module I have a font-face decl. with `src: url("../fonts/bla"` and this is literally in the blob, but of course that's wrong and it needs to be based on where the assets have been copied to.

For example for `loader: 'url-loader?name=assets/[name].[ext]',` I would expect the url to be changed to be `src: url("assets/fonts/bla"`, otherwise how would it find the file?

But also of course physical files don't get copied until I run this with ExtractTextPlugin, so I'm unsure how it would ever work in dev mode with a limit set?

Thanks for any pointers!

**Comment by michael-ciniawsky** [comment]
@DominicTobias Could you provide more info about your setup please? Maybe you are looking for something like `copy-webpack-plugin` or similar, which copys the physical files to the dest folder in case you don't **require** them within you're bundle

**Comment by DominicTobias** [comment]
Hi np it's too long since I was looking at this now so I'm going to close it 👍
