### ISSUE TITLE
Can I extract all Base64 images string into one separated trunk?

### ISSUE THREAD

**Issue by jin5354** [webpack-contrib/url-loader#56]
My project has many small images, which are tansformed into Base64 string and increase the bundle size by 70~kb. Can I separate all the base64 images into one separated asynchronous trunk to get better performance, or I can just use sprite image? Thanks for your help!

**Comment by michael-ciniawsky** [comment]
@jin5354 The loader itself does simply encode the file under a certain byte limit to DataURL's and a loader in general always works on chunk/file level. I think for what you are after, you will need to write/search for a plugin instead, which works on **complation** level (whole bundle) and implement this logic there.
