### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by talves** [webpack-contrib/url-loader#6]
I took a stab at this, but failed due to my lack of webpack knowledge.

I thought it would be great to have the limit support the svg extension mimetype (image/svg+xml)

[I found this on StackOverflow](http://stackoverflow.com/questions/11753485/set-img-src-to-dynamic-svg-element)

Any thoughts?

**Comment by iamstarkov** [comment]
is it still the best solution?

**Comment by ColCh** [comment]
Idea of using multiple loaders for SVG is far mo-o-ore good solution than just `raw-loader`.

Sorry mate,  I can't find issue thread discussion for this.

**Comment by iamstarkov** [comment]
prob you are talking about webpack/webpack#595

**Comment by NekR** [comment]
This is what I get from ``url-loader`` for svg (decoded base64 string):
```javascript
"module.exports = "<svg fill=\"#000000\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\">\n    <path d=\"M0 0h24v24H0z\" fill=\"none\"/>\n    <path d=\"M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z\"/>\n</svg>""
```

Obviously this is wrong xml document.

**Comment by NekR** [comment]
Oh, I got it, inline loader does not overrides default loader. It works, nevermind.

**Comment by alkema** [comment]
@ColCh Great idea to use `raw-loader` for inline SVG. :+1: Works perfectly.

**Comment by ColCh** [comment]
@alkema pleased to help :blush:

**Comment by alexandrbig** [comment]
Is it possible to load some svgs inline from one folder and all others like path only? 
Please help.

**Comment by iamstarkov** [comment]
@alexandrbig have two loader/ruler items with two different test regexps

**Comment by jasongrout** [comment]
For what it's worth, in JupyterLab we're using the url-loader with a mimetype specified, like this:

```
{ test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, use: 'url-loader?limit=10000&mimetype=image/svg+xml' }
```
(https://github.com/jupyterlab/jupyterlab/blob/bb7f8dabc2d4a927b325ca301ee02422522b7eeb/jupyterlab/staging/webpack.config.js#L134)
