### ISSUE TITLE
prefix specific css file urls paths 

### ISSUE THREAD

**Issue by newasmod** [webpack-contrib/url-loader#61]
set webpac.config to prefix url in background-image: url(prefix- path)
so if i have in css file something like:
.limage09o { background-image: url('/img/image.png'); }
i want webpack to add prefix to url('/img/image.png') like:
url('../../../../img/image.png')

**Comment by michael-ciniawsky** [comment]
@newasmod I think you will need to set that up with `css-loader` and you could try the `prefix` option aswell

**Comment by Genuifx** [comment]
@michael-ciniawsky bro, you can use publicPath to set up your project assets' prefix path. This is similar to the prefix.

**Comment by michael-ciniawsky** [comment]
@newasmod See @Genuifx comment 😛

**Comment by rofrol** [comment]
I fixed this by adding two more loader before `sass-loader`:
`'css-loader', 'resolve-url-loader', 'sass-loader'`

https://github.com/webpack-contrib/sass-loader#problems-with-url

**Comment by TonyLuo** [comment]
@Genuifx  when I try to set publicPath: "./", the css will refer to the current folder. is any option to override the publicPath for url-loader?
``
    {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        },
          options: {
          publicPath: '/'
        }
      }

![image](https://user-images.githubusercontent.com/3250305/30981213-46bef5c4-a449-11e7-8d3c-0f83b1e75755.png)

**Comment by Genuifx** [comment]
@TonyLuo This is my configuration, remind that you need `file-loader@0.10.0` cause url-loader dont support file-loader 1.0
 `{
                    test: /\.(jpg|png|gif|svg)$/,
                    exclude: [projectStorage],
                    loader: 'url-loader',
                    options: {
                        limit: 10000,
                        publicPath: '../',
                        // publicPath: (url)=>{
                        //     console.log(url);
                        //     return url;
                        // },
                        name: 'assets/[name].[hash:4].[ext]',
                    },
                }`

**Comment by TonyLuo** [comment]
@Genuifx it works. thanks so much!
