### ISSUE TITLE
about version upgrade

### ISSUE THREAD

**Issue by cenfun** [webpack-contrib/url-loader#63]
when you update "loader-utils" to "^1.0.2" from "0.2.x", you'd better update url-loader to "0.6.x" or "1.0.x".
because of loader-utils 1.x is used ES6 that's a big change but url-loader just change to 0.5.8 from 0.5.6.
it's lots of error when we use ~0.5.6

**Comment by d3viant0ne** [comment]
The update to loader-utils was limited to an internal API change not functionality. What it did do was force a NodeJS version beyond 4.3.x.

Support for .10 / .12 was dropped when NodeJS officially dropped their support of these versions. 

`Webpack will continue to drop support for versions as NodeJS does`

 This has been handled as a `patch` version for all loaders requiring the same change across the `webpack-contrib` org.
