### ISSUE TITLE
can disable base64 when required a file that less than the limit

### ISSUE THREAD

**Issue by xingangsun** [webpack-contrib/url-loader#65]
When I use this plugin, it will be encode all of the file that less than the limit, but sometimes I don't want to encode though its file size less than the limit of my configuration

**Comment by michael-ciniawsky** [comment]
@xingangsun use the exclude option in `webpack.config.js` and reorganise your files 

**webpack.config.js**
```js
{
   test: /\.png$/,
   use: { loader: 'url-loader', options: { limit: 8192 } },
   exclude: '/path/to/excluded/assets'
}
```

Otherwise send PR to propose a `exclude` options for discussion

**Comment by xingangsun** [comment]
ok, thanks a lot😊

**Comment by tbutman** [comment]
I was wanting to exclude certain assets that are below the limit as well. The problem is we used react-create-app and have not yet ejected, so we can't modify the webpack configs Is there any way to prevent the loader from inlining the data without ejecting and modifying the config?

**Comment by bishoywagih** [comment]
i have the same issue that i have to eject my application to re-configure webpack, so any update?

**Comment by evilebottnawi** [comment]
@bishoywagih react-create-app has option for limit

**Comment by bishoywagih** [comment]
@evilebottnawi where can i find that option, sorry i'm new to react.

**Comment by evilebottnawi** [comment]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L50
