### ISSUE TITLE
0.5.8 is a breaking change, prolly should treat it as 0.6.0

### ISSUE THREAD

**Issue by terencechow** [webpack-contrib/url-loader#66]
v0.5.7
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
errors
**If the current behavior is a bug, please provide the steps to reproduce.**
have a project with node 0.10 and use url-loader. you will get an error

**What is the expected behavior?**
no error

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

This post is mostly to make you aware that between v0.5.7 and v0.5.8 there is a breaking change where the `loader-utils` package switches from 0.2 to 1.0. That is a breaking change for anyone using a node version that does not understand `const` since `const` is a newer es6 keyword that does not exist in older versions of node. Our continuous delivery system failed on no changes on our part because we have `^0.5.7` in our `package.json` and the bump from 0.5.7 to 0.5.8 should have been considered a breaking change (for those of us with production systems using older node versions). Just an FYI.

**Comment by d3viant0ne** [comment]
If you are on Webpack 1.x and i'm betting you are, just `pin to 0.5.7` there won't be further updates so no need to target a range here. 

This isn't specific to url-loader , this is something that rolled down from a common library ( long story ). There is unfortunately, nothing I can do about it at this point though I don't disagree with what you are saying. Everything in the org will be getting a major with the application of `webpack-defaults` over the next two weeks which should move us past this.

Informational ...
If you are on `Webpack 2.x, Node < 4.3 is unsupported`. Webpack drops support for NodeJS versions as the Node organization does ( .10 & .12 are unsupported as of Oct / Dev 2016 respectively )
