### ISSUE TITLE
Documentation URL

### ISSUE THREAD

**Issue by svipben** [webpack-contrib/url-loader#68]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**
`Documentation: Using loaders` redirect you to old webpack website which is for v1, not for v2.

**What is the expected behavior?**
Redirect to new website which is for v2.

**Comment by michael-ciniawsky** [comment]
Will be fixed by #70

**Comment by d3viant0ne** [comment]
Closed by #77 77
