### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/url-loader#71]
**Do you want to request a *feature* or report a *bug*?**

Chore.

**What is the current behavior?**

Contain `.github` template.

**What is the expected behavior?**

Don't contain `.github` template.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Reduce package size

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Not required.

**Comment by d3viant0ne** [comment]
@evilebottnawi - This will be taken care of in #70 which has a properly defined `files` property in the `package.json`

**Comment by evilebottnawi** [comment]
@d3viant0ne thanks!
