### ISSUE TITLE
Url-loader plus useRelativePath after the entry into force, but no pictures in the dist directory

### ISSUE THREAD

**Issue by shaodahong** [webpack-contrib/url-loader#80]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
The picture is not compiled
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

nodejs: v7.10.0
webpack: 2.6.1
file-loader: 0.11.2
url-loader: 0.5.9

`{
            test: /\.(png|jpg|jpeg|gif|ico)$/i,
            use: {
                loader: "url-loader",
                options: {
                    limit: 10000,
                    name: 'static/images/[name].[hash:6].[ext]',
                    useRelativePath: true
                }
            }
        }, {
            test: /\.(svg|woff|woff2|ttf|eot)$/i,
            use: {
                loader: "file-loader",
                options: {
                    name: 'static/images/[name].[hash:6].[ext]',
                    useRelativePath: true
                }
            }
        }`
Url-loader plus useRelativePath after the entry into force, but no pictures in the dist directory

But not add useRelativePath css inside the generated image path is relative to the dist directory, I want is relative to the css file directory

Now dist in the css file in the picture path is correct, but the picture catalog but not this file

**Comment by hhhonzik** [comment]
+1 having the same problem, even without useRelativePath

**Comment by shaodahong** [comment]
@hhhonzik I have resolved using `publicPath: '../../'`

**Comment by evilebottnawi** [comment]
@shaodahong @hhhonzik `url-loader` don't modify path, seems issue(s) related to `file-loader`, thanks!
