### ISSUE TITLE
Feature request: Add an option to replace "file-loader" with any other customized loader

### ISSUE THREAD

**Issue by liujingbreak** [webpack-contrib/url-loader#82]
Current the url-loader is hard coded to fallback calling `file-loader` internally.
What I wish is that I can use a customized loader to replace `file-loader`, e.g.  `lib/dr-file-loader`

```js
{
	test: /\.(jpg|png|gif|svg|jpeg|eot|woff2|woff|ttf)$/,
	use: [
          {loader: 'lib/dr-file-loader'},
          {loader: 'lib/url-loader'},
        ]
}
```
Or 
```js
{
     test: /\.(jpg|png|gif|svg|jpeg|eot|woff2|woff|ttf)$/,
	use: [
          {loader: 'lib/url-loader', options: {
                    use: [ {loader: 'lib/dr-file-loader'} ]
                },
        ]
}

**Comment by evilebottnawi** [comment]
@webpack-contrib/org-maintainers what do your think about this?

**Comment by hulkish** [comment]
I think this is a good idea. I personally haven't had this need - but I can see why it would be useful. 

Maybe this can be better accounted for in the rules config api?

**Comment by michael-ciniawsky** [comment]
### `options.fallback`

```js
{
   loader: 'url-loader',
   options: { fallback: 'my-custom-loader' }
}
```

On the other hand requiring a file isn't that special, @liujingbreak what is your usecase for a custom loader, what functionality is `file-loader` missing atm ?

**Comment by DaxChen** [comment]
My use case will be:
If the image is less than limit, inline it;
If the image exceeds the limit, fall back to [responsive-loader](https://github.com/herrstucki/responsive-loader) or [resize-image-loader](https://github.com/puppybits/resize-image-loader) to generate multiple responsive images (for `<img srcSet />`.

Any thoughts on how can this be done?

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/url-loader/pull/88
