### ISSUE TITLE
Misleading documentation - options.prefix

### ISSUE THREAD

**Issue by mmarzantowicz** [webpack-contrib/url-loader#83]
There is an option mentioned in `READMEmd` in **Options** section called **prefix**. It is poorly documented and has no effect when used in `webpack.config.js` files. Can I create PR to remove it or it's on the todo list to be implemented at sometime?

**Comment by Genuifx** [comment]
[https://github.com/webpack-contrib/url-loader/issues/61](61) have a look, but the documentation do need an update(0_0)
