### ISSUE TITLE
Using the base64 export as a component

### ISSUE THREAD

**Issue by RomainGoncalves** [webpack-contrib/url-loader#86]
Hello,

I have created a library. In this library I have a component that uses a SVG icon like so:

```javascript
// Simplified
import VerifiedAwardBadge from './verified.svg';

export const GetIcon = () => {
      return <ActiveAwardBadge />;
}
```
When calling `<GetIcon />` from the library's project, it works just fine.

I then build the project, publish it on NPM and try using it into my other project. There when I call `<GetIcon />` I get this error:

```
Uncaught Error: Invalid tag:data:image/svg+xml;base64,dmFyIFJlYWN0ID0gcmVxdWlyZSgncmVhY...
```

I understand that during the build my library exported the SVG in base64, it's now present into the library, but then when trying to load it, it tries to do
```javascript
<data:image/svg+xml;base64,dmFyIFJlYWN0ID0gcmVxdWlyZSgncmVhY... />
```
and that's not a valid element.

My question is then, how can I get to use that SVG/base64 version properly?

My webpack config for the build of the library (showing only the module for the SVG as I believe that's the only relevant one):

```javascript
module: {
      loaders: [
        {
          test: /\.(png|woff|woff2|eot|ttf|svg)$/,
          use: ['url-loader?limit=100000'],
        },
      ],
    },
```

And webpack config for the project consuming the library (project based on create-react-app):

```javascript
module: {
      loaders: [
      {
       // This handles SVG in general
        test: /\.svg$/i,
        exclude: [/(\/flags)/, path.resolve('node_modules')],
        loader: 'svg-react-loader',
      },
      {
        // This one handles a specific external library's SVG
        test: /(\/flags)/,
        loader: 'svg-url-loader',
      },
]}
```

Thanks for any help you could provide.

**Comment by michael-ciniawsky** [comment]
Don't use the `url-loader` in your case, `base64` encoding is not mandatory for SVG 

- [svg-url-loader](https://www.npmjs.com/package/svg-url-loader)
-  `file-loader`

**webpack.config.js**
```diff
module: {
  rules: [
    {
-     test: /\.(png|woff|woff2|eot|ttf|svg)$/,
+     test: /\.(png|woff|woff2|eot|ttf)$/,  
+     use: {
+        loader: 'url-loader'
+        options: { limit: 100000 }
+     }
    },
+   {
+     test: /\.svg$/,
+     use: {
+        loader: 'svg-url-loader' || 'file-loader',
+     },
+   }
  ]
}
```

**Comment by RomainGoncalves** [comment]
Thanks I will try that and get back to you.

**Comment by hpeikari** [comment]
@RomainGoncalves 
Any development on this? I have the exact same issue. The suggested solution didn't help.
I wonder if you could fix it somehow?

**Comment by AndrejGajdos** [comment]
I have the same issue as well.

**Comment by AndrejGajdos** [comment]
I have the same issue as well.
