### ISSUE TITLE
mime@1.3.6 is vulernable

### ISSUE THREAD

**Issue by ntucker** [webpack-contrib/url-loader#92]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
mime dependency is at 1.3.6

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
mime should be 1.4.x

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
https://nodesecurity.io/advisories/535

**Comment by ntucker** [comment]
https://github.com/webpack-contrib/url-loader/commit/ced5990b9fef7e1ccf71d69f26c527f8c0a3c87a fixes the dependency to allow for 1.4.x versions, so we really just need a release

**Comment by michael-ciniawsky** [comment]
The dependency uses `^` so within the semver minor/patch range it should install the latest available on a fresh install anyways, but will be released as soon as someone from the release team as time of course :)

**Comment by ntucker** [comment]
I'm just saying a release is important now since there's a vulnerability

**Comment by michael-ciniawsky** [comment]
Yep, I understand  and we are aware, but it shouldn't be that urgent since `^` will likely pull `mime` v1.4.1 already, the dependency minimum should be set to v1.4.1 just in case nevertheless

**Comment by ntucker** [comment]
Oh, I mean the last released version of this library didn't use ^. Usage of ^ was done in https://github.com/webpack-contrib/url-loader/commit/ced5990b9fef7e1ccf71d69f26c527f8c0a3c87a

**Comment by d3viant0ne** [comment]
It's out on the `next` dist-tag for the time being.
