### ISSUE TITLE
[v0.6.0] Breaks option pass through (`schema`)

### ISSUE THREAD

**Issue by LarsOL** [webpack-contrib/url-loader#93]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The validation stops the 'name' option from being a valid entry.
```
{
   test: /\.(png|jpg|gif|svg)$/,
   use: [
            {
                loader: 'url-loader',
                options: {
                      name: 'img/[hash].[ext]',
                      limit: 10000
                 }
             }
   ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The 'name' should be passed through into 'file-loader' if the fallback loader is triggered, like the previous version.

Or provide a 'official' way of passing options to the fallback loader

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Mac/ Linux. Node 7.9

**Comment by michael-ciniawsky** [comment]
Ooops... 😛  my bad, PR is [here](https://github.com/webpack-contrib/url-loader/issues/94)
