### ISSUE TITLE
[v0.6.0] ValidationError using `limit` as `{String}`

### ISSUE THREAD

**Issue by huineng** [webpack-contrib/url-loader#95]
with the current release > 0.6.0 you published a day ago
i'm now getting build errors with webpack and angular 
webpack 3.6
angular 4.4.4

Module build failed: Validation Error
URL Loader Invalid Options
options['name'] should NOT have additional properties
options.limit should be number

**Comment by evilebottnawi** [comment]
@huineng please update to `0.6.1`, thank you!

**Comment by JounQin** [comment]
@evilebottnawi It still breaks on string query like `url-loader?limit=10000`

**Comment by damonbauer** [comment]
@evilebottnawi Seeing the same errors on `0.6.1`:

```js
{
  test: /experiments\/.*\/assets\/.*\.(png|jpg|svg)$/,
  use: ['url-loader?limit=8192']
}
```

Results in:
```
Module build failed: ModuleBuildError: Module build failed: Validation Error
URL Loader Invalid Options
options.limit should be number
```

**Comment by huineng** [comment]
yes that's what i meant with > 0.6.0 (also 0.6.1) 

Now i changed from 
```
 {
        test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
        loader: 'url-loader?limit=10000&name=public/fonts/[name].[ext]&mimetype=application/font-woff'
      },
```

to 
```
{
                test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: {
                            limit: 10000,
                            name: 'public/fonts/[name].[ext]',
                            mimetype: 'application/font-woff'
                        }
                    }
                ]
            },
```
and this works

**Comment by evilebottnawi** [comment]
@damonbauer seems `['url-loader?limit=8192']` limit interpreted as `string`

**Comment by evilebottnawi** [comment]
PR: https://github.com/webpack-contrib/url-loader/pull/96
