### ISSUE TITLE
packing font-awesome css run

### ISSUE THREAD

**Issue by JohnieXu** [webpack-contrib/url-loader#97]
when i packing .font-awesome.css with url-loader, i got  **404error**
i checked the css after packing, 
### the 404 tips path is:
```
static/css/static/fonts/
```
### problems:
there shouldn't have this `/css/static`

**Comment by michael-ciniawsky** [comment]
Please show your current config (`webpack.config.js`)

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if more info is provided
