### ISSUE TITLE
can't pass parameters into fallback

### ISSUE THREAD

**Issue by fiter92** [webpack-contrib/url-loader#99]
I'm using the latest versions of webpack, url and file loaders and etc.

If I run `fallback: 'file-loader'` everything is ok, but if I wat to save fonts into the fonts directory 
`fallback: 'file-loader?name=fonts/[name].[ext]'`  I've got an error:
```
ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0
Module build failed: Error: Cannot find module 'file-loader?name=fonts/[name].[ext]'
```
Is there any way to save large font into the fonts path?

**Comment by michael-ciniawsky** [comment]
```js
{
   test: /\.(eot|woff|...)$/,
   use: [ 
     { 
       loader: 'url-loader', 
       options: {
         limit: /* your size limit */, 
         name: 'fonts/[name].[ext]' 
      }
    } 
  ] 
}
```
